-- Seed: works（从老站 Markdown 提取，6 作品 x 7 语言）
-- cover_asset_id 占位 NULL（Phase 1）

-- aether
INSERT INTO works (brand_id, slug, sort_order, status, published_at, cover_asset_id,
  title, tagline, role, services, overview, highlights, body, meta)
VALUES (
  (SELECT id FROM brands WHERE slug='werkero'),
  'aether',
  4,
  'published',
  now(),
  NULL,
  '{"en": "Aether", "zh-cn": "Aether", "zh-tw": "Aether", "fr": "Aether", "de": "Aether", "ru": "Aether", "ja": "Aether"}',
  '{"en": "AI-powered inspiration capture and execution.", "zh-cn": "AI 驱动的灵感捕捉与执行。", "zh-tw": "AI 驅動的靈感捕捉與執行。", "fr": "Capture d''inspiration et exécution propulsées par l''IA.", "de": "KI-gestütztes Festhalten und Umsetzen von Inspiration.", "ru": "ИИ-захват вдохновения и его исполнение.", "ja": "AIによるひらめきの捕捉と実行。"}',
  '{"en": "Product design & engineering", "zh-cn": "产品设计与工程", "zh-tw": "產品設計與工程", "fr": "Design produit & ingénierie", "de": "Produktdesign & Engineering", "ru": "Дизайн продукта и инженерия", "ja": "プロダクトデザイン＆エンジニアリング"}',
  '{"en": ["Product design", "Web app", "AI integration"], "zh-cn": ["产品设计", "网站应用", "AI 集成"], "zh-tw": ["產品設計", "網站應用", "AI 整合"], "fr": ["Design produit", "Application web", "Intégration IA"], "de": ["Produktdesign", "Web-App", "KI-Integration"], "ru": ["Дизайн продукта", "Веб-приложение", "ИИ-интеграция"], "ja": ["プロダクトデザイン", "Webアプリ", "AIインテグレーション"]}',
  '{"en": "Aether captures fleeting inspiration with AI and turns it into executable next steps.", "zh-cn": "Aether 用 AI 捕捉稍纵即逝的灵感，并把它变成可执行的下一步。", "zh-tw": "Aether 用 AI 捕捉稍縱即逝的靈感，並把它變成可執行的下一步。", "fr": "Aether capture l''inspiration fugace grâce à l''IA et la transforme en prochaines étapes exécutables.", "de": "Aether hält flüchtige Inspiration mit KI fest und macht daraus umsetzbare nächste Schritte.", "ru": "Aether ловит мимолётное вдохновение с помощью ИИ и превращает его в исполнимые следующие шаги.", "ja": "Aether はAIで儚いひらめきを捉え、実行可能な次のステップに変える。"}',
  '{"en": ["Frictionless capture, anywhere", "AI turns notes into action plans", "Glassmorphism interface"], "zh-cn": ["随时随地，无摩擦捕捉", "AI 把笔记变成行动计划", "玻璃拟态界面"], "zh-tw": ["隨時隨地，無摩擦捕捉", "AI 把筆記變成行動計畫", "玻璃擬態介面"], "fr": ["Capture sans friction, partout", "L''IA transforme les notes en plans d''action", "Interface en glassmorphism"], "de": ["Reibungsloses Capturing, überall", "KI macht aus Notizen Aktionspläne", "Glassmorphism-Interface"], "ru": ["Захват без трения, где угодно", "ИИ превращает заметки в планы действий", "Glassmorphism-интерфейс"], "ja": ["どこでも、摩擦のないキャプチャ", "AIがメモを実行計画に変換", "グラスモーフィズムのインターフェース"]}',
  '{"en": "Ideas die in inboxes. Aether treats every captured thought as the start of a workflow — the AI reads intent, proposes structure, and hands back something you can act on.\n\nBuilt for people whose best thinking happens away from the desk.", "zh-cn": "灵感死在收件箱里。Aether 把每个捕捉到的想法都当作工作流的起点——AI 读懂意图、给出结构，交还给你可以行动的东西。\n\n为那些最好的思考发生在办公桌之外的人而造。", "zh-tw": "靈感死在收件匣裡。Aether 把每個捕捉到的想法都當作工作流的起點——AI 讀懂意圖、給出結構，交還給你可以行動的東西。\n\n為那些最好的思考發生在辦公桌之外的人而造。", "fr": "Les idées meurent dans les boîtes de réception. Aether traite chaque pensée capturée comme le début d''un workflow — l''IA lit l''intention, propose une structure et rend quelque chose d''actionnable.\n\nConçu pour ceux dont les meilleures idées naissent loin du bureau.", "de": "Ideen sterben in Postfächern. Aether behandelt jeden festgehaltenen Gedanken als Workflow-Start — die KI liest die Intention, schlägt Struktur vor und gibt etwas Handlungsfähiges zurück.\n\nGebaut für alle, deren bestes Denken abseits des Schreibtischs passiert.", "ru": "Идеи умирают во входящих. Aether относится к каждой пойманной мысли как к началу workflow — ИИ считывает намерение, предлагает структуру и возвращает то, с чем можно действовать.\n\nСоздан для тех, чьи лучшие мысли приходят вне офиса.", "ja": "アイデアは受信箱で死ぬ。Aether は捉えた思考のすべてをワークフローの起点として扱う——AIが意図を読み取り、構造を提案し、行動できるものを返す。\n\n最高の思考がデスクの外で生まれる人のために。"}',
  '{"en": {"title": "Aether", "description": "AI-powered inspiration capture and execution."}, "zh-cn": {"title": "Aether", "description": "AI 驱动的灵感捕捉与执行。"}, "zh-tw": {"title": "Aether", "description": "AI 驅動的靈感捕捉與執行。"}, "fr": {"title": "Aether", "description": "Capture d''inspiration et exécution propulsées par l''IA."}, "de": {"title": "Aether", "description": "KI-gestütztes Festhalten und Umsetzen von Inspiration."}, "ru": {"title": "Aether", "description": "ИИ-захват вдохновения и его исполнение."}, "ja": {"title": "Aether", "description": "AIによるひらめきの捕捉と実行。"}}'
);

-- ai-archives
INSERT INTO works (brand_id, slug, sort_order, status, published_at, cover_asset_id,
  title, tagline, role, services, overview, highlights, body, meta)
VALUES (
  (SELECT id FROM brands WHERE slug='werkero'),
  'ai-archives',
  2,
  'published',
  now(),
  NULL,
  '{"en": "AI Archives", "zh-cn": "AI 机要室", "zh-tw": "AI 機要室", "fr": "AI Archives", "de": "AI Archives", "ru": "AI Archives", "ja": "AI Archives"}',
  '{"en": "An archive of AI history and AI news.", "zh-cn": "AI 历史与 AI 新闻的档案馆。", "zh-tw": "AI 歷史與 AI 新聞的檔案館。", "fr": "Une archive de l''histoire de l''IA et de son actualité.", "de": "Ein Archiv für KI-Geschichte und KI-News.", "ru": "Архив истории ИИ и новостей ИИ.", "ja": "AIの歴史とAIニュースのアーカイブ。"}',
  '{"en": "Concept, design & engineering", "zh-cn": "概念、设计与工程", "zh-tw": "概念、設計與工程", "fr": "Concept, design & ingénierie", "de": "Konzept, Design & Engineering", "ru": "Концепция, дизайн и инженерия", "ja": "コンセプト・デザイン＆エンジニアリング"}',
  '{"en": ["Editorial design", "Web app"], "zh-cn": ["编辑设计", "网站应用"], "zh-tw": ["編輯設計", "網站應用"], "fr": ["Design éditorial", "Application web"], "de": ["Editorial Design", "Web-App"], "ru": ["Редакционный дизайн", "Веб-приложение"], "ja": ["エディトリアルデザイン", "Webアプリ"]}',
  '{"en": "AI Archives (AI 机要室) is a living archive documenting the history of artificial intelligence alongside its daily news.", "zh-cn": "AI 机要室是一座活的档案馆，记录人工智能的历史，也记录它每天的新闻。", "zh-tw": "AI 機要室是一座活的檔案館，記錄人工智慧的歷史，也記錄它每天的新聞。", "fr": "AI Archives (AI 机要室) est une archive vivante qui documente l''histoire de l''intelligence artificielle ainsi que son actualité quotidienne.", "de": "AI Archives (AI 机要室) ist ein lebendiges Archiv, das die Geschichte der künstlichen Intelligenz und ihre täglichen News dokumentiert.", "ru": "AI Archives (AI 机要室) — живой архив, документирующий историю искусственного интеллекта и его ежедневные новости.", "ja": "AI Archives（AI 机要室）は、人工知能の歴史と日々のニュースを記録する生きたアーカイブ。"}',
  '{"en": ["Covers both AI history and AI news", "Archive-grade editorial presentation", "Fully multilingual reading experience"], "zh-cn": ["兼顾 AI 历史与 AI 新闻", "档案级的编辑呈现", "全多语言阅读体验"], "zh-tw": ["兼顧 AI 歷史與 AI 新聞", "檔案級的編輯呈現", "全多語言閱讀體驗"], "fr": ["Couvre l''histoire et l''actualité de l''IA", "Présentation éditoriale digne d''une archive", "Expérience de lecture entièrement multilingue"], "de": ["Deckt KI-Geschichte und KI-News ab", "Editoriale Präsentation auf Archiv-Niveau", "Vollständig mehrsprachiges Leseerlebnis"], "ru": ["Охватывает историю и новости ИИ", "Редакционная подача архивного уровня", "Полностью мультиязычный опыт чтения"], "ja": ["AIの歴史とニュースの両方をカバー", "アーカイブ級の編集プレゼンテーション", "完全多言語の読書体験"]}',
  '{"en": "The project treats AI''s story with the seriousness of an archive: every era documented, every development filed. History gives the news context; the news keeps the history alive.\n\nIt is designed to be read slowly — a counterweight to the feed-speed coverage of the field.", "zh-cn": "这个项目以档案的严肃对待 AI 的故事：每个时代都被记录，每个进展都被归档。历史给新闻以语境，新闻让历史保持鲜活。\n\n它是为慢阅读设计的——对抗信息流速度的配速。", "zh-tw": "這個專案以檔案的嚴肅對待 AI 的故事：每個時代都被記錄，每個進展都被歸檔。歷史給新聞以語境，新聞讓歷史保持鮮活。\n\n它是為慢閱讀設計的——對抗資訊流速度的配速。", "fr": "Le projet traite l''histoire de l''IA avec le sérieux d''une archive : chaque époque documentée, chaque avancée classée. L''histoire donne un contexte à l''actualité ; l''actualité garde l''histoire vivante.\n\nConçu pour une lecture lente — un contrepoids à la couverture à la vitesse du flux.", "de": "Das Projekt behandelt die Geschichte der KI mit der Ernsthaftigkeit eines Archivs: jede Ära dokumentiert, jeder Fortschritt abgelegt. Geschichte gibt den News Kontext; News halten die Geschichte lebendig.\n\nFür langsames Lesen gebaut — ein Gegengewicht zur Feed-Geschwindigkeit.", "ru": "Проект относится к истории ИИ с серьёзностью архива: каждая эпоха задокументирована, каждое достижение подшито. История даёт новостям контекст; новости поддерживают историю живой.\n\nСоздан для медленного чтения — противовес скорости ленты.", "ja": "このプロジェクトはAIの物語をアーカイブの真剣さで扱う：すべての時代を記録し、すべての進展をファイリング。歴史がニュースに文脈を与え、ニュースが歴史を生かし続ける。\n\nスローリーディングのために設計——フィード速度の報道への対抗軸。"}',
  '{"en": {"title": "AI Archives", "description": "An archive of AI history and AI news."}, "zh-cn": {"title": "AI 机要室", "description": "AI 历史与 AI 新闻的档案馆。"}, "zh-tw": {"title": "AI 機要室", "description": "AI 歷史與 AI 新聞的檔案館。"}, "fr": {"title": "AI Archives", "description": "Une archive de l''histoire de l''IA et de son actualité."}, "de": {"title": "AI Archives", "description": "Ein Archiv für KI-Geschichte und KI-News."}, "ru": {"title": "AI Archives", "description": "Архив истории ИИ и новостей ИИ."}, "ja": {"title": "AI Archives", "description": "AIの歴史とAIニュースのアーカイブ。"}}'
);

-- arkhyx-blog
INSERT INTO works (brand_id, slug, sort_order, status, published_at, cover_asset_id,
  title, tagline, role, services, overview, highlights, body, meta)
VALUES (
  (SELECT id FROM brands WHERE slug='werkero'),
  'arkhyx-blog',
  5,
  'published',
  now(),
  NULL,
  '{"en": "Arkhyx Blog", "zh-cn": "Arkhyx Blog", "zh-tw": "Arkhyx Blog", "fr": "Arkhyx Blog", "de": "Arkhyx Blog", "ru": "Arkhyx Blog", "ja": "Arkhyx Blog"}',
  '{"en": "An open-source blog project.", "zh-cn": "一个开源博客项目。", "zh-tw": "一個開源部落格專案。", "fr": "Un projet de blog open-source.", "de": "Ein Open-Source-Blogprojekt.", "ru": "Блог-проект с открытым исходным кодом.", "ja": "オープンソースのブログプロジェクト。"}',
  '{"en": "Design & engineering", "zh-cn": "设计与工程", "zh-tw": "設計與工程", "fr": "Design & ingénierie", "de": "Design & Engineering", "ru": "Дизайн и инженерия", "ja": "デザイン＆エンジニアリング"}',
  '{"en": ["Open source", "Web app"], "zh-cn": ["开源", "网站应用"], "zh-tw": ["開源", "網站應用"], "fr": ["Open source", "Application web"], "de": ["Open Source", "Web-App"], "ru": ["Открытый код", "Веб-приложение"], "ja": ["オープンソース", "Webアプリ"]}',
  '{"en": "Arkhyx Blog is an open-source blog project — a clean, fast publishing setup anyone can run.", "zh-cn": "Arkhyx Blog 是一个开源博客项目——干净、快速，任何人都能跑起来。", "zh-tw": "Arkhyx Blog 是一個開源部落格專案——乾淨、快速，任何人都能跑起來。", "fr": "Arkhyx Blog est un projet de blog open-source — une configuration de publication propre et rapide, que chacun peut héberger.", "de": "Arkhyx Blog ist ein Open-Source-Blogprojekt — ein sauberes, schnelles Publishing-Setup für alle.", "ru": "Arkhyx Blog — блог-проект с открытым кодом: чистая и быстрая издательская платформа, которую может запустить каждый.", "ja": "Arkhyx Blog はオープンソースのブログプロジェクト——クリーンで高速、誰でも運用できるパブリッシング環境。"}',
  '{"en": ["Open-source and self-hostable", "Minimal, reading-first design", "Built as a public learning artifact"], "zh-cn": ["开源，可自行托管", "极简，以阅读为先的设计", "作为公开的学习记录构建"], "zh-tw": ["開源，可自行託管", "極簡，以閱讀為先的設計", "作為公開的學習紀錄構建"], "fr": ["Open-source et auto-hébergeable", "Design minimal, priorité à la lecture", "Construit comme un artefact public d''apprentissage"], "de": ["Open-Source und selbst hostbar", "Minimal, lesen zuerst", "Als öffentliches Lern-Artefakt gebaut"], "ru": ["Открытый код, можно хостить самому", "Минимализм, чтение на первом месте", "Построен как публичный учебный материал"], "ja": ["オープンソース、セルフホスト可能", "ミニマル、読書ファーストのデザイン", "公開学習の記録として構築"]}',
  '{"en": "Some projects are for shipping; this one is for sharing. Arkhyx Blog is built in the open so the decisions, mistakes, and trade-offs are all visible.\n\nA reminder that the studio''s craft improves when the process is public.", "zh-cn": "有些项目为交付，这个为分享。Arkhyx Blog 在开放中构建，决策、错误和权衡全部可见。\n\n提醒工作室：过程公开时，手艺才会更好。", "zh-tw": "有些專案為交付，這個為分享。Arkhyx Blog 在開放中構建，決策、錯誤和權衡全部可見。\n\n提醒工作室：過程公開時，手藝才會更好。", "fr": "Certains projets sont faits pour livrer ; celui-ci est fait pour partager. Arkhyx Blog est construit en public : décisions, erreurs et arbitrages sont visibles.\n\nUn rappel que le craft du studio s''améliore quand le processus est public.", "de": "Manche Projekte sind zum Shippedwerden da; dieses zum Teilen. Arkhyx Blog entsteht in der Öffentlichkeit — Entscheidungen, Fehler und Trade-offs sind sichtbar.\n\nEine Erinnerung: Das Craft des Studios wächst, wenn der Prozess öffentlich ist.", "ru": "Некоторые проекты создаются ради релиза; этот — ради того, чтобы делиться. Arkhyx Blog строится открыто: решения, ошибки и компромиссы видны всем.\n\nНапоминание: мастерство студии растёт, когда процесс публичен.", "ja": "届けるためのプロジェクトもあれば、分かち合うためのプロジェクトもある。Arkhyx Blog はオープンに構築される——判断も失敗もトレードオフも見える。\n\nスタジオの技芸は、プロセスが公開されるときに磨かれる、というリマインダー。"}',
  '{"en": {"title": "Arkhyx Blog", "description": "An open-source blog project."}, "zh-cn": {"title": "Arkhyx Blog", "description": "一个开源博客项目。"}, "zh-tw": {"title": "Arkhyx Blog", "description": "一個開源部落格專案。"}, "fr": {"title": "Arkhyx Blog", "description": "Un projet de blog open-source."}, "de": {"title": "Arkhyx Blog", "description": "Ein Open-Source-Blogprojekt."}, "ru": {"title": "Arkhyx Blog", "description": "Блог-проект с открытым исходным кодом."}, "ja": {"title": "Arkhyx Blog", "description": "オープンソースのブログプロジェクト。"}}'
);

-- awarely
INSERT INTO works (brand_id, slug, sort_order, status, published_at, cover_asset_id,
  title, tagline, role, services, overview, highlights, body, meta)
VALUES (
  (SELECT id FROM brands WHERE slug='werkero'),
  'awarely',
  3,
  'published',
  now(),
  NULL,
  '{"en": "Awarely", "zh-cn": "Awarely", "zh-tw": "Awarely", "fr": "Awarely", "de": "Awarely", "ru": "Awarely", "ja": "Awarely"}',
  '{"en": "Cross-border e-commerce brand, growing into AI home decision-making.", "zh-cn": "跨境电商品牌，正在走向 AI 居家决策。", "zh-tw": "跨境電商品牌，正在走向 AI 居家決策。", "fr": "Marque e-commerce transfrontalière, en route vers la décision IA à la maison.", "de": "Cross-Border-E-Commerce-Marke, auf dem Weg zur KI-Haushaltsentscheidung.", "ru": "Трансграничный e-commerce бренд на пути к ИИ-решениям для дома.", "ja": "越境ECブランド、AIホーム意思決定へ。"}',
  '{"en": "Brand & product engineering", "zh-cn": "品牌与产品工程", "zh-tw": "品牌與產品工程", "fr": "Marque & ingénierie produit", "de": "Brand & Product Engineering", "ru": "Бренд и продуктовая инженерия", "ja": "ブランド＆プロダクトエンジニアリング"}',
  '{"en": ["Brand identity", "E-commerce", "AI product"], "zh-cn": ["品牌识别", "电商", "AI 产品"], "zh-tw": ["品牌識別", "電商", "AI 產品"], "fr": ["Identité de marque", "E-commerce", "Produit IA"], "de": ["Markenidentität", "E-Commerce", "KI-Produkt"], "ru": ["Айдентика бренда", "E-commerce", "ИИ-продукт"], "ja": ["ブランドアイデンティティ", "EC", "AIプロダクト"]}',
  '{"en": "Awarely began as a cross-border e-commerce brand and is growing toward AI-assisted home decisions and family health companionship.", "zh-cn": "Awarely 起步于跨境电商，正在走向 AI 辅助的居家决策与家庭健康陪伴。", "zh-tw": "Awarely 起步於跨境電商，正在走向 AI 輔助的居家決策與家庭健康陪伴。", "fr": "Awarely a commencé comme marque e-commerce transfrontalière et évolue vers l''aide à la décision domestique par IA et l''accompagnement santé familial.", "de": "Awarely startete als Cross-Border-E-Commerce-Marke und wächst in Richtung KI-gestützter Haushaltsentscheidungen und familiärer Gesundheitsbegleitung.", "ru": "Awarely начинался как трансграничный e-commerce бренд и движется в сторону ИИ-помощи в домашних решениях и сопровождения семейного здоровья.", "ja": "Awarely は越境ECブランドとして始まり、AIによる家庭の意思決定支援とファミリーヘルスの同伴へ向かっている。"}',
  '{"en": ["Cross-border retail brand and storefront", "Expanding into AI home decision support", "Family health companion direction"], "zh-cn": ["跨境零售品牌与店面", "正在拓展 AI 居家决策支持", "家庭健康陪伴方向"], "zh-tw": ["跨境零售品牌與店面", "正在拓展 AI 居家決策支援", "家庭健康陪伴方向"], "fr": ["Marque retail transfrontalière et boutique", "Expansion vers l''aide à la décision domestique par IA", "Direction compagnon santé familial"], "de": ["Cross-Border-Retail-Marke und Storefront", "Ausbau Richtung KI-Haushaltsentscheidungen", "Familiäre Gesundheitsbegleitung als Richtung"], "ru": ["Трансграничный ритейл-бренд и витрина", "Расширение в ИИ-поддержку домашних решений", "Направление — компаньон для семейного здоровья"], "ja": ["越境リテールブランドとストア", "AI家庭意思決定支援への拡張", "ファミリーヘルス同伴という方向性"]}',
  '{"en": "Awarely proves a brand can start in commerce and earn its way into people''s homes. The retail operation funds the longer bet: an AI companion for household decisions and health.\n\nOne brand, two horizons — selling today, caring tomorrow.", "zh-cn": "Awarely 证明一个品牌可以从商业起步，一路走进人们的家。零售业务为更长远的赌注提供资金：为家庭决策和健康服务的 AI 陪伴。\n\n一个品牌，两个地平线——今天做生意，明天做陪伴。", "zh-tw": "Awarely 證明一個品牌可以從商業起步，一路走進人們的家。零售業務為更長遠的賭注提供資金：為家庭決策和健康服務的 AI 陪伴。\n\n一個品牌，兩個地平線——今天做生意，明天做陪伴。", "fr": "Awarely prouve qu''une marque peut naître dans le commerce et se frayer un chemin jusqu''aux foyers. L''activité retail finance le pari long : un compagnon IA pour les décisions du foyer et la santé.\n\nUne marque, deux horizons — vendre aujourd''hui, prendre soin demain.", "de": "Awarely beweist: Eine Marke kann im Handel starten und sich bis in die Wohnzimmer vorarbeiten. Das Retail-Geschäft finanziert die lange Wette: ein KI-Begleiter für Haushaltsentscheidungen und Gesundheit.\n\nEine Marke, zwei Horizonte — heute verkaufen, morgen begleiten.", "ru": "Awarely доказывает: бренд может родиться в коммерции и дойти до гостиных. Ритейл финансирует долгую ставку — ИИ-компаньона для домашних решений и здоровья.\n\nОдин бренд, два горизонта — сегодня продавать, завтра заботиться.", "ja": "Awarely は証明する：ブランドはコマースから生まれ、家庭のリビングまでたどり着ける。リテール事業が長期の賭けを支える——家庭の意思決定と健康のためのAIコンパニオン。\n\n一つのブランド、二つの地平線——今日は売り、明日は寄り添う。"}',
  '{"en": {"title": "Awarely", "description": "Cross-border e-commerce brand, growing into AI home decision-making."}, "zh-cn": {"title": "Awarely", "description": "跨境电商品牌，正在走向 AI 居家决策。"}, "zh-tw": {"title": "Awarely", "description": "跨境電商品牌，正在走向 AI 居家決策。"}, "fr": {"title": "Awarely", "description": "Marque e-commerce transfrontalière, en route vers la décision IA à la maison."}, "de": {"title": "Awarely", "description": "Cross-Border-E-Commerce-Marke, auf dem Weg zur KI-Haushaltsentscheidung."}, "ru": {"title": "Awarely", "description": "Трансграничный e-commerce бренд на пути к ИИ-решениям для дома."}, "ja": {"title": "Awarely", "description": "越境ECブランド、AIホーム意思決定へ。"}}'
);

-- kyvero
INSERT INTO works (brand_id, slug, sort_order, status, published_at, cover_asset_id,
  title, tagline, role, services, overview, highlights, body, meta)
VALUES (
  (SELECT id FROM brands WHERE slug='werkero'),
  'kyvero',
  6,
  'published',
  now(),
  NULL,
  '{"en": "Kyvero", "zh-cn": "Kyvero", "zh-tw": "Kyvero", "fr": "Kyvero", "de": "Kyvero", "ru": "Kyvero", "ja": "Kyvero"}',
  '{"en": "A sibling project in the -ero brand family.", "zh-cn": "-ero 品牌家族的兄弟项目。", "zh-tw": "-ero 品牌家族的兄弟專案。", "fr": "Un projet frère dans la famille de marques -ero.", "de": "Ein Schwesterprojekt in der -ero-Markenfamilie.", "ru": "Родственный проект в бренд-семье -ero.", "ja": "-eroブランドファミリーの兄弟プロジェクト。"}',
  '{"en": "Brand & engineering", "zh-cn": "品牌与工程", "zh-tw": "品牌與工程", "fr": "Marque & ingénierie", "de": "Brand & Engineering", "ru": "Бренд и инженерия", "ja": "ブランド＆エンジニアリング"}',
  '{"en": ["Brand system", "Web app"], "zh-cn": ["品牌体系", "网站应用"], "zh-tw": ["品牌體系", "網站應用"], "fr": ["Système de marque", "Application web"], "de": ["Markensystem", "Web-App"], "ru": ["Система бренда", "Веб-приложение"], "ja": ["ブランドシステム", "Webアプリ"]}',
  '{"en": "Kyvero is a sibling project in the -ero brand family — sharing the studio''s design language and engineering standards.", "zh-cn": "Kyvero 是 -ero 品牌家族的兄弟项目——共享工作室的设计语言与工程标准。", "zh-tw": "Kyvero 是 -ero 品牌家族的兄弟專案——共享工作室的設計語言與工程標準。", "fr": "Kyvero est un projet frère dans la famille de marques -ero — il partage le langage design et les standards d''ingénierie du studio.", "de": "Kyvero ist ein Schwesterprojekt in der -ero-Markenfamilie — es teilt Designsprache und Engineering-Standards des Studios.", "ru": "Kyvero — родственный проект в бренд-семье -ero: разделяет дизайн-язык и инженерные стандарты студии.", "ja": "Kyvero は-eroブランドファミリーの兄弟プロジェクト——スタジオのデザイン言語とエンジニアリング基準を共有する。"}',
  '{"en": ["Part of the Kyvero · Laurero · Werkero family", "Shared design DNA across projects", "Independent product, shared craft"], "zh-cn": ["Kyvero · Laurero · Werkero 家族一员", "项目间共享设计 DNA", "独立产品，共享手艺"], "zh-tw": ["Kyvero · Laurero · Werkero 家族一員", "專案間共享設計 DNA", "獨立產品，共享手藝"], "fr": ["Membre de la famille Kyvero · Laurero · Werkero", "ADN design partagé entre projets", "Produit indépendant, craft partagé"], "de": ["Teil der Familie Kyvero · Laurero · Werkero", "Geteilte Design-DNA über Projekte hinweg", "Unabhängiges Produkt, geteiltes Craft"], "ru": ["Член семьи Kyvero · Laurero · Werkero", "Общий дизайн-ДНК между проектами", "Независимый продукт, общее мастерство"], "ja": ["Kyvero · Laurero · Werkero ファミリーの一員", "プロジェクト間で共有されるデザインDNA", "独立したプロダクト、共有される技芸"]}',
  '{"en": "Kyvero, Laurero, Werkero — the family shares a suffix and a standard. Each project stands alone, but all of them carry the same care in design and engineering.\n\nThe -ero projects are the studio''s long-term compound interest.", "zh-cn": "Kyvero、Laurero、Werkero——家族共享一个后缀和一套标准。每个项目独立成立，但都带着同样的设计与工程用心。\n\n-ero 项目是工作室的长期复利。", "zh-tw": "Kyvero、Laurero、Werkero——家族共享一個後綴和一套標準。每個專案獨立成立，但都帶著同樣的設計與工程用心。\n\n-ero 專案是工作室的長期複利。", "fr": "Kyvero, Laurero, Werkero — la famille partage un suffixe et un standard. Chaque projet existe seul, mais tous portent le même soin.\n\nLes projets -ero sont les intérêts composés du studio.", "de": "Kyvero, Laurero, Werkero — die Familie teilt ein Suffix und einen Standard. Jedes Projekt steht für sich, aber alle tragen dieselbe Sorgfalt.\n\nDie -ero-Projekte sind der Zinseszins des Studios.", "ru": "Kyvero, Laurero, Werkero — семья разделяет суффикс и стандарт. Каждый проект самостоятелен, но все несут одинаковую заботу.\n\nПроекты -ero — сложный процент студии.", "ja": "Kyvero、Laurero、Werkero——ファミリーは接尾辞と基準を共有する。各プロジェクトは独立しながら、同じ丁寧さを持つ。\n\n-eroプロジェクトはスタジオの長期複利。"}',
  '{"en": {"title": "Kyvero", "description": "A sibling project in the -ero brand family."}, "zh-cn": {"title": "Kyvero", "description": "-ero 品牌家族的兄弟项目。"}, "zh-tw": {"title": "Kyvero", "description": "-ero 品牌家族的兄弟專案。"}, "fr": {"title": "Kyvero", "description": "Un projet frère dans la famille de marques -ero."}, "de": {"title": "Kyvero", "description": "Ein Schwesterprojekt in der -ero-Markenfamilie."}, "ru": {"title": "Kyvero", "description": "Родственный проект в бренд-семье -ero."}, "ja": {"title": "Kyvero", "description": "-eroブランドファミリーの兄弟プロジェクト。"}}'
);

-- laurero
INSERT INTO works (brand_id, slug, sort_order, status, published_at, cover_asset_id,
  title, tagline, role, services, overview, highlights, body, meta)
VALUES (
  (SELECT id FROM brands WHERE slug='werkero'),
  'laurero',
  1,
  'published',
  now(),
  NULL,
  '{"en": "Laurero", "zh-cn": "Laurero", "zh-tw": "Laurero", "fr": "Laurero", "de": "Laurero", "ru": "Laurero", "ja": "Laurero"}',
  '{"en": "AI gaokao application advisor that dares to tell the truth.", "zh-cn": "敢说真话的 AI 高考志愿填报顾问。", "zh-tw": "敢說真話的 AI 高考志願填報顧問。", "fr": "Conseiller IA d''orientation gaokao qui ose dire la vérité.", "de": "KI-Berater für die Gaokao-Bewerbung, der die Wahrheit sagt.", "ru": "ИИ-консультант по gaokao, который не боится говорить правду.", "ja": "真実を語ることを恐れないAI高考志願アドバイザー。"}',
  '{"en": "Product design & engineering", "zh-cn": "产品设计与工程", "zh-tw": "產品設計與工程", "fr": "Design produit & ingénierie", "de": "Produktdesign & Engineering", "ru": "Дизайн продукта и инженерия", "ja": "プロダクトデザイン＆エンジニアリング"}',
  '{"en": ["Product strategy", "Web app", "Data pipeline"], "zh-cn": ["产品策略", "网站应用", "数据管道"], "zh-tw": ["產品策略", "網站應用", "資料管道"], "fr": ["Stratégie produit", "Application web", "Pipeline de données"], "de": ["Produktstrategie", "Web-App", "Datenpipeline"], "ru": ["Стратегия продукта", "Веб-приложение", "Дата-пайплайн"], "ja": ["プロダクト戦略", "Webアプリ", "データパイプライン"]}',
  '{"en": "Laurero helps Chinese students choose university applications with honest, data-backed guidance — full companionship through the whole decision.", "zh-cn": "Laurero 用诚实、有数据依据的指导帮中国学生做志愿选择——全程陪伴整个决策过程。", "zh-tw": "Laurero 用誠實、有資料依據的指導幫中國學生做志願選擇——全程陪伴整個決策過程。", "fr": "Laurero aide les étudiants chinois à choisir leurs candidatures universitaires avec des conseils honnêtes, fondés sur les données — un accompagnement complet.", "de": "Laurero hilft chinesischen Schülern bei der Uni-Bewerbung mit ehrlicher, datenbasierter Beratung — volle Begleitung durch die ganze Entscheidung.", "ru": "Laurero помогает китайским студентам выбирать вузы — честные рекомендации на основе данных и сопровождение на всём пути решения.", "ja": "Laurero は中国の学生の大学志願選択を支援——誠実でデータに裏打ちされた指導と、決定までのフル同伴。"}',
  '{"en": ["Credit-based freemium: 100 free credits, paid tiers up to lifetime", "Policy data refreshed weekly from official sources", "Built on honest advice, not inflated promises"], "zh-cn": ["积分制免费增值：100 免费积分，付费档至终身", "政策数据每周从官方来源更新", "立足诚实建议，不做夸大承诺"], "zh-tw": ["積分制免費增值：100 免費積分，付費檔至終身", "政策資料每週從官方來源更新", "立足誠實建議，不做誇大承諾"], "fr": ["Freemium à crédits : 100 crédits gratuits, offres payantes jusqu''au lifetime", "Données politiques actualisées chaque semaine depuis des sources officielles", "Des conseils honnêtes, pas des promesses gonflées"], "de": ["Freemium mit Credits: 100 Gratis-Credits, Paid-Stufen bis Lifetime", "Wöchentliche Policy-Updates aus offiziellen Quellen", "Ehrliche Beratung statt überzogener Versprechen"], "ru": ["Freemium на кредитах: 100 бесплатных кредитов, платные тарифы вплоть до lifetime", "Еженедельное обновление данных из официальных источников", "Честные советы вместо раздутых обещаний"], "ja": ["クレジット制フリーミアム：100無料クレジット、有料はライフタイムまで", "公式ソースから毎週更新される政策データ", "誠実な助言が基盤、誇大な約束はしない"]}',
  '{"en": "Laurero started from a simple frustration: application advice was either expensive, generic, or dishonest. The product combines official policy data, admission records, and score distributions into one conversational assistant.\n\nThe pricing is deliberately accessible — a small credit packs model with a generous free tier — so honest guidance isn''t a luxury good.", "zh-cn": "Laurero 源于一种简单的不满：志愿建议要么贵、要么泛、要么不诚实。它把官方政策数据、录取记录和分段表装进一个对话助手。\n\n定价刻意亲民——小额积分包加慷慨的免费档——让诚实的指导不是奢侈品。", "zh-tw": "Laurero 源於一種簡單的不滿：志願建議要麼貴、要麼泛、要麼不誠實。它把官方政策資料、錄取紀錄和分段表裝進一個對話助手。\n\n定價刻意親民——小額積分包加慷慨的免費檔——讓誠實的指導不是奢侈品。", "fr": "Laurero est né d''une frustration simple : les conseils d''orientation étaient chers, génériques ou malhonnêtes. Le produit combine données politiques officielles, dossiers d''admission et distributions de notes dans un assistant conversationnel.\n\nLe tarif est volontairement accessible — petits packs de crédits et offre gratuite généreuse — pour que l''honnêteté ne soit pas un luxe.", "de": "Laurero entstand aus simplem Frust: Bewerbungsberatung war teuer, generisch oder unehrlich. Das Produkt bündelt offizielle Policy-Daten, Zulassungsdaten und Notenverteilungen in einem conversational Assistant.\n\nDas Pricing ist bewusst zugänglich — kleine Credit-Pakete plus großzügige Free-Tier — damit ehrliche Beratung kein Luxus ist.", "ru": "Laurero родился из простого разочарования: консультации по поступлению были дорогими, шаблонными или нечестными. Продукт соединяет официальные данные, статистику приёма и распределения баллов в одном диалоговом ассистенте.\n\nЦены сознательно доступные — небольшие пакеты кредитов и щедрый бесплатный тариф, — чтобы честность не была роскошью.", "ja": "Laurero はシンプルな不満から生まれた：志願アドバイスは高額か、画一的か、不誠実だった。公式政策データ、合格実績、得点分布を一つの対話アシスタントに統合。\n\n料金は意図的に手頃に——少額クレジットと寛大な無料枠——誠実さが贅沢品にならないように。"}',
  '{"en": {"title": "Laurero", "description": "AI gaokao application advisor that dares to tell the truth."}, "zh-cn": {"title": "Laurero", "description": "敢说真话的 AI 高考志愿填报顾问。"}, "zh-tw": {"title": "Laurero", "description": "敢說真話的 AI 高考志願填報顧問。"}, "fr": {"title": "Laurero", "description": "Conseiller IA d''orientation gaokao qui ose dire la vérité."}, "de": {"title": "Laurero", "description": "KI-Berater für die Gaokao-Bewerbung, der die Wahrheit sagt."}, "ru": {"title": "Laurero", "description": "ИИ-консультант по gaokao, который не боится говорить правду."}, "ja": {"title": "Laurero", "description": "真実を語ることを恐れないAI高考志願アドバイザー。"}}'
);
